# This manifest will inject a X second delay to P% of the requests to the service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: django-virtualservice
  namespace: default
spec:
  hosts:
  - "api.m0d4s.me"
  gateways:
  - django-gateway
  http:
  - match:
    - uri:
        prefix: /.well-known/acme-challenge/
    route:
    - destination:
        host: cm-acme-http-solver-qswgj.aks-istio-ingress.svc.cluster.local
        port:
          number: 8089
  - fault:
      delay:
        percentage:
          value: 50
        fixedDelay: 5s
    match:
    - uri:
        prefix: /api/
    route:
    - destination:
        host: django-api.default.svc.cluster.local
        port:
          number: 8000
