version: '3.1'

services:
  django:
    hostname: drf.fssp.m0d4s.me
    image: elyass359/fssp-django:v1
    # build:
    #   context: fssp_django/
    #   dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./profilePics:/app/profilePics:rw
    depends_on:
      - postgres
    networks:
      - backend
  
  vuejs:
    hostname: vue.fssp.m0d4s.me
    build:
      context: fssp_vuejs/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - django
    networks:
      - backend

  postgres:
    hostname: postgres.fssp.m0d4s.me
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: fssp_user
      POSTGRES_PASSWORD: fssp_passme+.
      POSTGRES_DB: fssp
    ports:
      - "5432:5432"
    networks:
      - backend
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
