apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: m0d4s@duck.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: istio

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: django-app-cert
  namespace: aks-istio-ingress
spec:
  secretName: django-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.m0d4s.me
  dnsNames:
  - api.m0d4s.me

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vue-app-cert
  namespace: aks-istio-ingress
spec:
  secretName: vue-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fssp.m0d4s.me
  dnsNames:
  - fssp.m0d4s.me