apiVersion: v1
kind: ServiceAccount
metadata:
  name: django-service-account
  namespace: default

---
apiVersion: v1
kind: Secret
type : kubernetes.io/service-account-token
metadata:
  name: django-service-account-token
  annotations: 
    kubernetes.io/service-account.name: django-service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: django-rbac
  namespace: default
rules:
# Allow the service account to create and manage Volumes , and mount them to the pods of the deployment 'django-deployment'
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["svc"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: django-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: django-rbac
