apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: django-gateway
  namespace: default
spec:
  selector:
    istio: aks-istio-ingressgateway-external
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*" # This is a wildcard host, NEEDS TO BE CHANGED
    # tls:
    #   httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "api.m0d4s.me"
    tls:
      mode: SIMPLE
      credentialName: django-app-tls
---
# Django VirtualService
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: django-virtualservice
  namespace: default
spec:
  hosts:
  - "api.m0d4s.me"
  gateways:
  - django-gateway
  http:
  - match:
    - uri:
        prefix: /.well-known/acme-challenge/
    route:
    - destination:
        host: cm-acme-http-solver-qswgj.aks-istio-ingress.svc.cluster.local
        port:
          number: 8089
  - match:
    - uri:
        prefix: /api/
    route:
    - destination:
        host: django-api.default.svc.cluster.local
        port:
          number: 8000

---
# Vue Gateway
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vue-gateway
  namespace: default
spec:
  selector:
    istio: aks-istio-ingressgateway-external
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*" # This is a wildcard host, NEEDS TO BE CHANGED
    # tls:
    #   httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "fssp.m0d4s.me"
    tls:
      mode: SIMPLE
      credentialName: vue-app-tls
---
# Vue VirtualService
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vue-virtualservice
  namespace: default
spec:
  hosts:
  - "fssp.m0d4s.me"
  gateways:
  - vue-gateway
  http:
  - match:
    - uri:
        prefix: /.well-known/acme-challenge/
    route:
    - destination:
        host: cm-acme-http-solver-ws59f.aks-istio-ingress.svc.cluster.local
        port:
          number: 8089
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: vuejs-service.default.svc.cluster.local
        port:
          number: 80