# Generated by Django 5.0.2 on 2024-02-27 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='object',
            fields=[
                ('OId', models.AutoField(primary_key=True, serialize=False)),
                ('dateTimeCreated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='userAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('profilePic', models.ImageField(upload_to='profilePics/')),
                ('status2FA', models.BooleanField()),
                ('criticalLockStat', models.BooleanField()),
                ('idleTime', models.IntegerField()),
            ],
            options={
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.object')),
                ('myFile', models.FileField(upload_to='files/')),
                ('fileName', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
            ],
            options={
                'ordering': ['fileName'],
            },
            bases=('api.object',),
        ),
        migrations.CreateModel(
            name='secret',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.object')),
                ('content', models.CharField(max_length=4100)),
            ],
            bases=('api.object',),
        ),
        migrations.AddField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount'),
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('NotifID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('operation', models.CharField(max_length=250)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
