# Generated by Django 5.0.2 on 2024-02-27 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240227_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='secret',
            name='secretID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='object_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.object'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='object_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.object'),
        ),
    ]
