# Generated by Django 5.0.2 on 2024-02-27 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_objevent_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='activityLog',
            fields=[
                ('objID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('operation', models.CharField(max_length=250)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.useraccount')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='share',
            fields=[
                ('shareID', models.AutoField(primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.object')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraccount')),
                ('sharedWith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharedWith', to='api.useraccount')),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
        migrations.DeleteModel(
            name='objEvent',
        ),
    ]
